server:
    port: 8081
auth:
    token:
        issuer:
            urls:
                google: https://hdash.alok.digital/home/auth/google/validate/id-token
                home-stack-auth: https://hdash.alok.digital/home/auth/home/token/validate