server:
    port: 8081
auth:
    token:
        issuer:
            urls:
                google: http://home-auth-service:8081/home/auth/google/validate/id-token
                home-stack-auth: http://home-auth-service:8081/home/auth/home/token/validate